name: Sync to Hugging Face Space

on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "rosenobzor@gmail.com"
          git config --global user.name "rosenobzor"
          git remote add huggingface https://rosenobzor:$HF_TOKEN@huggingface.co/spaces/warp360/9
          git push --force huggingface main

